### ISSUE TITLE
Current main-branch version of buildpack isn't deployable

### ISSUE THREAD

**Issue by arthfl** [cloudfoundry/php-buildpack#1208]
Ahoy,

The current main branch (7b37993) seems to have a bug that lets a very simple app deployment fail currently:
```
2025-12-16T10:14:02.29+0100 [STG/0] OUT -----> Finalizing PHP
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Copied rewrite binary to .bp/bin
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Loading default options from embedded config
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Set PHP_DEFAULT = 8.1.32 from manifest
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Set PHP_81_LATEST = 8.1.32
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Set PHP_82_LATEST = 8.2.28
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Set PHP_83_LATEST = 8.3.21
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Using web server: httpd (from options.json)
   2025-12-16T10:14:02.29+0100 [STG/0] OUT Created start script for httpd
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Created pre-start wrapper script
   2025-12-16T10:14:02.29+0100 [STG/0] OUT DEBUG: Created PHP runtime directory: /tmp/contents667600700/deps/0/php/var/run
   2025-12-16T10:14:02.29+0100 [STG/0] OUT PHP buildpack finalize phase complete
   2025-12-16T10:14:05.17+0100 [STG/0] ERR Failed to build droplet release: buildpack's release output invalid: yaml: line 4: mapping values are not allowed in this context
   2025-12-16T10:14:05.18+0100 [STG/0] OUT Exit status 224
   2025-12-16T10:14:05.69+0100 [STG/0] OUT Cell c2ce894c-7146-4119-8f66-065da745909f stopping instance e2f5e0b4-9f57-4b0c-b9a1-84a86c076b35
   2025-12-16T10:14:05.69+0100 [STG/0] OUT Cell c2ce894c-7146-4119-8f66-065da745909f destroying container for instance e2f5e0b4-9f57-4b0c-b9a1-84a86c076b35
   2025-12-16T10:14:05.75+0100 [API/0] ERR Failed to stage build: staging failed
```

This is from a minimal hello-world-ish sample app we deploy daily to test our (Dynatrace) buildpack integration.
The manifest looks like
```
---
applications:
  - name: php-sample
    memory: 256M
    instances: 1
    buildpacks:
        - https://github.com/cloudfoundry/php-buildpack.git
    env:
      BP_DEBUG: true
```

This is happening since November 21st 2025 constantly.

The latest stable release of the php-buildpack works just fine.

**Comment by ramonskie** [comment]
it should now be fixed within 9fad270dfc2a1effa9e6c60520e937f02c73ae8f

**Comment by arthfl** [comment]
> it is fixed.

It is not:
`2026-01-22T10:19:36.08+0100 [APP/PROC/WEB/0] ERR /home/vcap/app/.bp/bin/rewrite: line 7: /home/vcap/app/.bp/scripts/install_go.sh: No such file or directory`

This was with a simple manifest that used the main branch:
```
---
applications:
  - name: php-apache-test
    memory: 256M
    instances: 1
    buildpacks:
      - https://github.com/cloudfoundry/php-buildpack.git
    env:
      BP_DEBUG: true
```

**Comment by akf** [comment]
Hi @ramonskie, apologies for the slow response. 

I tried using the current `remove-rewrite-binary-clean` branch and it appears to have used the {PHP_83_LATEST} (php version 8.3.30 was installed) and #{WEBDIR} variables. 

I still see the post-deploy problems running php scripts in the app. This is a Drupal app and we have a post-deploy step that uses `cf ssh` to run some `drush` commands. I inherited this app after another team left, so I'm still teasing out what they did that might be considered unusual, but here's what I'm seeing: 

The post-deploy script executes `cf ssh` from the CI runner. The command explicitly sets the PATH: 
```
cf ssh "${PROJECT}-drupal-${CF_SPACE}" --command "PATH=/home/vcap/deps/1/bin:/home/vcap/deps/0/bin:/usr/local/bin:/usr/bin:/bin:/home/vcap/app/php/bin:/home/vcap/app/php/sbin:/home/vcap/app/php/bin:/home/vcap/app/vendor/drush/drush DRUPAL_UPDATE_OR_INSTALL=${DRUPAL_UPDATE_OR_INSTALL} app/scripts/post-deploy && echo 'Successfully completed post deploy!' || echo 'Failed to complete post deploy!'"
```
That post-deploy script hits an error as soon as it runs a `php` command. It starts with a string of warnings about "Unable to load dynamic library ..." -- here's the first of those: 
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'bz2.so' (tried: /tmp/app/php/lib/php/extensions/no-debug-non-zts-20230831/bz2.so (/tmp/app/php/lib/php/extensions/no-debug-non-zts-20230831/bz2.so: cannot open shared object file: No such file or directory), /tmp/app/php/lib/php/extensions/no-debug-non-zts-20230831/bz2.so.so (/tmp/app/php/lib/php/extensions/no-debug-non-zts-20230831/bz2.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```
... and eventually produces a fatal error: 
```
Error: Class "PDO" not found in /home/vcap/app/web/sites/default/settings.cloudgov.php on line 90 #0 /home/vcap/app/web/sites/default/settings.php(923): include()
```

Another thing that's different, and probably a little special about this project, is that normally I can `cf ssh` to the app when it's launched successfully and run `php -v`.  So someone did something to set the PATH for a login shell. Whatever it was, it's not getting applied when I build with this buildpack. It might be something that happens later in that post-deploy script. 

I do see a difference between the app as deployed with the 4.6.28 branch and this one that might be a clue: 

v.4.6.28: /home/vcap/profile.d has a `000_multi-supply.sh` file, which is absent when I deploy with the 5.x buildpack. This script sets PATH, LD_LIBRARY_PATH, and LIBRARY_PATH. I don't think it's the whole story, as setting those variables as defined in that file doesn't fix anything for me, but you can see a reference to this file here: https://github.com/cloudfoundry/php-buildpack/blob/0747055e9fbd0f10c5b2e38818aba0f6ced8419e/vendor/github.com/cloudfoundry/libbuildpack/stager_unix.go#L10

Its contents wind up looking like this for our app (which uses both the php-buildpack and apt-buildpack): 
```
if [[ ! -z "${PATH:-}" ]]; then
	export PATH="$DEPS_DIR/1/bin:$DEPS_DIR/0/bin:$PATH"
else
	export PATH="$DEPS_DIR/1/bin:$DEPS_DIR/0/bin"
fi
if [[ ! -z "${LD_LIBRARY_PATH:-}" ]]; then
	export LD_LIBRARY_PATH="$DEPS_DIR/1/lib:$DEPS_DIR/0/lib:$LD_LIBRARY_PATH"
else
	export LD_LIBRARY_PATH="$DEPS_DIR/1/lib:$DEPS_DIR/0/lib"
fi
if [[ ! -z "${LIBRARY_PATH:-}" ]]; then
	export LIBRARY_PATH="$DEPS_DIR/1/lib:$DEPS_DIR/0/lib:$LIBRARY_PATH"
else
	export LIBRARY_PATH="$DEPS_DIR/1/lib:$DEPS_DIR/0/lib"
```

**Comment by ramonskie** [comment]
i pushed 2 new commits to that branch https://github.com/cloudfoundry/php-buildpack/tree/remove-rewrite-binary-clean
- add standalone php app
- add ADDITIONAL_PREPROCESS_CMDS

see also https://github.com/cloudfoundry/php-buildpack/blob/remove-rewrite-binary-clean/docs/V4_V5_MIGRATION_GAP_ANALYSIS.md
